---
AWSTemplateFormatVersion: 2010-09-09


Description: Document storage & management.


Parameters:

   BucketName:
      Description: Name of the S3 bucket.
      Type: String
      Default: djsp-documents

   RoleName:
      Description: Name of the IAM role.
      Type: String
      Default: documents-manager

   TrusteeArn:
      Description: ARN of the trustee.
      Type: String
      Default: arn:aws:iam::659664769788:user/david


Resources:

   Bucket:
      Type: AWS::S3::Bucket
      Properties: {
         BucketEncryption: {
            ServerSideEncryptionConfiguration: [
               {
                  ServerSideEncryptionByDefault: {
                     SSEAlgorithm: AES256,
                  },
               },
            ],
         },
         BucketName: {
            Ref: BucketName,
         },
         PublicAccessBlockConfiguration: {
            BlockPublicAcls: true,
            BlockPublicPolicy: true,
            IgnorePublicAcls: true,
            RestrictPublicBuckets: true,
         },
      }

   BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties: {
         Bucket: {
            Ref: Bucket,
         },
         PolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Sid: RestrictUploads,
                  Principal: '*',
                  Action: [
                     's3:PutObject',
                     's3:PutObjectTagging',
                  ],
                  Resource: [
                     {
                        'Fn::Sub': '${Bucket.Arn}/*',
                     },
                  ],
                  Condition: {
                     StringNotLike: {
                        'aws:userId': [
                           {
                              'Fn::Sub': '${DocumentsManager.RoleId}:*',
                           },
                        ],
                     },
                  },
                  Effect: Deny,
               },
               {
                  Sid: RestrictObjectStorageClasses,
                  Principal: '*',
                  Action: [
                     's3:PutObject',
                  ],
                  Resource: [
                     {
                        'Fn::Sub': '${Bucket.Arn}/*',
                     },
                  ],
                  Condition: {
                     StringNotEquals: {
                        's3:x-amz-storage-class': [
                           STANDARD,
                           STANDARD_IA,
                        ],
                     },
                  },
                  Effect: Deny,
               },
               {
                  Sid: PreventDeletion,
                  Principal: '*',
                  Action: [
                     's3:DeleteObject',
                  ],
                  Resource: [
                     {
                        'Fn::GetAtt': [
                           Bucket,
                           Arn,
                        ],
                     },
                     {
                        'Fn::Sub': '${Bucket.Arn}/*',
                     },
                  ],
                  Effect: Deny,
               },
            ],
         },
      }

   DocumentsManager:
      Type: AWS::IAM::Role
      Properties: {
         AssumeRolePolicyDocument: {
            Version: 2012-10-17,
            Statement: [
               {
                  Principal: {
                     AWS: [
                        {
                           Ref: TrusteeArn,
                        },
                     ],
                  },
                  Action: [
                     'sts:AssumeRole',
                  ],
                  Effect: Allow,
               },
            ],
         },
         Description: {
            'Fn::Sub': 'Manages documents in bucket ${Bucket}.',
         },
         Policies: [
            {
               PolicyName: documents,
               PolicyDocument: {
                  Version: 2012-10-17,
                  Statement: [
                     {
                        Sid: Arbeitgeberbescheinigungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Arbeitgeberbescheinigungen/20??-??-??.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 Arbeitgeber,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/Arbeitgeber': [
                                 Smaato,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Gehaltsabrechnungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Gehaltsabrechnungen/20??/??.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 Arbeitgeber,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/Arbeitgeber': [
                                 Smaato,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Kontoauszuege,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Kontoauszüge/??????????/20??-??-??_20??-??-??.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 Bank,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/Bank': [
                                 DKB,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Kreditkartenabrechnungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Kreditkartenabrechnungen/*/20??-??-??_20??-??-??.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 Bank,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/Bank': [
                                 DKB,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Lohnsteuerbescheinigungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Lohnsteuerbescheinigungen/20??.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 Arbeitgeber,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/Arbeitgeber': [
                                 Smaato,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Meldebestaetigungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Meldebestätigungen/*.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 PLZ,
                                 years,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/PLZ': '?????',
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                     {
                        Sid: Rechnungen,
                        Action: [
                           's3:PutObject',
                           's3:PutObjectTagging',
                        ],
                        Resource: [
                           {
                              'Fn::Sub': '${Bucket.Arn}/Rechnungen/*/*.pdf'
                           },
                        ],
                        Condition: {
                           'ForAllValues:StringLike': {
                              's3:RequestObjectTagKeys': [
                                 date,
                                 deductable,
                                 years,
                              ],
                           },
                           StringEquals: {
                              's3:RequestObjectTag/deductable': [
                                 no,
                                 yes,
                              ],
                           },
                           StringLike: {
                              's3:RequestObjectTag/date': '20??.??.??',
                              's3:RequestObjectTag/years': '20??',
                           },
                        },
                        Effect: Allow,
                     },
                  ],
               },
            },
         ],
         RoleName: {
            Ref: RoleName,
         },
      }
