---
AWSTemplateFormatVersion: 2010-09-09


Description: Paperwork storage & management.


Resources:
   Bucket:
      Type: AWS::S3::Bucket
      Properties: {
         BucketEncryption: {
            ServerSideEncryptionConfiguration: [
               {
                  ServerSideEncryptionByDefault: {
                     SSEAlgorithm: AES256,
                  },
               },
            ],
         },
      }
